FROM python:3.9-slim

WORKDIR /app

COPY requirements_front.txt .
RUN pip install --no-cache-dir -r requirements_front.txt

COPY front.py .
COPY .streamlit/config.toml .streamlit/

EXPOSE 8501

ENV STREAMLIT_SERVER_PORT=8501
ENV STREAMLIT_SERVER_ADDRESS=0.0.0.0

CMD ["streamlit", "run", "front.py"]